version: '3.8'
services:
  t1:
    image: postgres
    environment:
      - "POSTGRES_DB=Jardineria"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pswJardineria"
    container_name: CMPpostgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks: 
      netred:
          ipv4_address: 172.150.10.1
    ports:
      - "5433:5432"
  t2:
    container_name: cmpappjardineria
    image: cmpappjardineria
    environment:
      - USER=mjmgtaller
      - PASSWORD=mjmgtaller
      - REPO=https://github.com/morgadodesarrollador/ApiJardineriaNest.git
      - DB_HOST=172.20.10.10
      - DB_PORT=5432
    networks: 
      netred:
          ipv4_address: 172.150.10.2
    ports:
      - "3000:3001"
networks:
  netred:
    ipam:
      driver: default 
      config:
        - subnet: 172.150.10.0/24